# pure = Purify version, mpic++

SHELL = /bin/sh

# ---------------------------------------------------------------------
# compiler/archive settings
# specify flags and libraries needed for your compiler and MPI installation

PURE_CC =	purify -best-effort -follow-child-processes=yes \
                -cache-dir=/tmp/purify -chain-length=20 
CC =  	        g++34 -Wall -m64 -DPURIFY_HATES_HASHLITTLE
CCFLAGS =	-g $(shell mpic++ --showme:compile) 
DEPFLAGS =	-M
ARCHIVE =	ar
ARFLAGS =	-rc
SIZE =		size

# ---------------------------------------------------------------------
# build rules and dependencies
# no need to edit this section

# Library target

lib:	$(OBJ)
	$(ARCHIVE) $(ARFLAGS) $(EXE) $(OBJ)

# Compilation rules

%.o:%.cpp
	$(CC) $(CCFLAGS) $(EXTRA_INC) -c $<

%.d:%.cpp
	$(CC) $(CCFLAGS) $(EXTRA_INC) $(DEPFLAGS) $< > $@

# Individual dependencies

DEPENDS = $(OBJ:.o=.d)
include $(DEPENDS)
