# mpicxx = any machine with MPI compiler wrappers, mpicxx

SHELL = /bin/sh

## -------------------------------------------------------------------
## Check 'BOOST_HOME' on the system you are using and set it appropriately.
## The 'TACC_BOOST_DIR' is 'BOOST_HOME' in XSEDE Ranger cluster system.
##
BOOST_HOME = $(TACC_BOOST_DIR)

# ---------------------------------------------------------------------
# compiler/archive settings
# specify flags and libraries needed for your compiler and MPI installation

CC = 		mpicxx
CCFLAGS =   -O2 -I$(BOOST_HOME)/include
DEPFLAGS =	-M
ARCHIVE =	ar
ARFLAGS =	-rc
SIZE =		size

# ---------------------------------------------------------------------
# build rules and dependencies
# no need to edit this section

# Library target

lib:	$(OBJ)
	$(ARCHIVE) $(ARFLAGS) $(EXE) $(OBJ)

# Compilation rules

%.o:%.cpp
	$(CC) $(CCFLAGS) $(EXTRA_INC) -c $<

%.d:%.cpp
	$(CC) $(CCFLAGS) $(EXTRA_INC) $(DEPFLAGS) $< > $@

# Individual dependencies

DEPENDS = $(OBJ:.o=.d)
include $(DEPENDS)
