# mpicxx = any machine with MPI compiler wrappers, mpicxx

SHELL = /bin/sh

BOOST_INCLUDE = $(TACC_BOOST_INC)

# ---------------------------------------------------------------------
# compiler/archive settings
# specify flags and libraries needed for your compiler and MPI installation

CC = 		mpicxx
CCFLAGS =   -O2 -I$(BOOST_INCLUDE) 
DEPFLAGS =	-M
ARCHIVE =	ar
ARFLAGS =	-rc
SIZE =		size

# ---------------------------------------------------------------------
# build rules and dependencies
# no need to edit this section

# Library target

lib:	$(OBJ)
	$(ARCHIVE) $(ARFLAGS) $(EXE) $(OBJ)

# Compilation rules

%.o:%.cpp
	$(CC) $(CCFLAGS) $(EXTRA_INC) -c $<

%.d:%.cpp
	$(CC) $(CCFLAGS) $(EXTRA_INC) $(DEPFLAGS) $< > $@

# Individual dependencies

DEPENDS = $(OBJ:.o=.d)
include $(DEPENDS)
