#$ -N r2048
#$ -cwd
#$ -o $JOB_NAME.o$JOB_ID
#$ -j n
#$ -A TG-DEB100001 
#$ -q normal
#$ -pe 16way 2048
#$ -V
#$ -l h_rt=24:00:00
#$ -M sulsj0270@gmail.com
#$ -m be

sh ranger-for-loop-run.sh

#set -x

#time ibrun ../mrblast -db - -dbsize 12494903041 -evalue 1e-4 -num_threads 1 -window_size 0 -word_size 11 -searchsp 0 -num_descriptions 500 -num_alignments 10000 -penalty -5 -reward 4  -lcase_masking -dust yes -soft_masking true -max_target_seqs 2147483647


